### PR TITLE
Merge dev/home into development

### PR DESCRIPTION
**Pull request by fedgut**
the main feature for dev/home has been built, requesting code review to merge into development

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @fedgut , 👋 You have done a great job in this project 👏 

 > Did you inform student success team about working alone?  If not kindly inform.

#### Behaviour

* [x] It has functional `login` page (authentication WITHOUT password, just providing a user email) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/login_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] microverse's automated tests are failing, I think mainly because your project requires a password which not necessary.
image

----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

**Comment by fedgut** [comment]
Yeah! The student success team is aware that this is a solo project! after this project ill get anew partner. thank you for your concern!

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required

Hello @fedgut 

You did a really nice job :smile: However, to move on there are some changes that you should do

1. As @imhta said in the last review, you should make the user logged in using his email. It's a requirement as specified [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/login_requirement.png)

2. You need to add **indexes** for referential fields from `user_events` table

Kindly make the suggested changes and submit a new code review request.
Thank you.

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

**Comment by fedgut** [comment]
> # Changes required
> 
> Hello @fedgut
> 
> You did a really nice job smile However, to move on there are some changes that you should do
> 
>     1. As @imhta said in the last review, you should make the user logged in using his email. It's a requirement as specified [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/login_requirement.png)
> 
>     2. You need to add **indexes** for referential fields from `user_events` table
> 
> 
> Kindly make the suggested changes and submit a new code review request.
> Thank you.
> 
> **Mael FOSSO**
> [Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

Thank you! I indeed had done something else! this time I double-checked to make sure I was understanding the requirements

**Review by uche-inyama — APPROVED** [review]
## Approved

Hi team,

Go ahead with the next project.

### ``` Remember to resolve conflict ``` :point_down: 

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Pull request merged**
